# Generated by Django 2.1.7 on 2019-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppsAppleStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=150)),
                ('n_citacoes', models.IntegerField()),
                ('size_bytes', models.IntegerField()),
                ('price', models.FloatField()),
                ('prime_genre', models.CharField(max_length=50)),
            ],
        ),
    ]
